starter
ISTE-500-501-TeamWatchHill/frontend pull request #52
Opened 2023-03-29 01:08 UTC by aag7593

- [ ] Admin view for header
- [ ] Admin view for buttons

2023-04-15 23:09 UTC, vsoler27 commented
im begging u to finish this so we can merge

2023-04-16 00:07 UTC, abp6318 requested changes
Really fucking good work. Few small things to look at; removing console logs and comments is low priority imo.

Amazing work girly! Vicky and I are geeking out at how good this all looks :)

2023-04-16 00:07 UTC, abp6318 commented on src/components/navbar/navbar.js
> +                    </tr>
Can we add /teamsanduniversities to this? That way admins can still view the `team/:id` pages should they want to?

2023-04-16 00:07 UTC, abp6318 commented on src/components/teamblock/teamblock.js
>  const TeamBlock = (props) => {
Remove any commented code if possible

2023-04-16 01:55 UTC, vsoler27 commented on src/components/editpopup/editpopup.js
> +                            <option key={0} value={JSON.stringify(nothing)}>{nothing.description}</option>
same thing as null methinks

2023-04-16 04:00 UTC, aag7593 commented on src/components/editpopup/editpopup.js
> +            "teamID": teamSelected._id,
Ah shit I knew I missed a part- I can look at that tomorrow morning

2023-04-16 14:53 UTC, abp6318 approved these changes
slayed -- making changes in another PR so we can get this stuff in main

2023-04-16 14:54 UTC, merged